drop table if exists comments;
drop table if exists bookings;
drop table if exists items;
drop table if exists requests;
drop table if exists users;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists requests (
    id int8 generated BY DEFAULT AS IDENTITY NOT NULL,
    description varchar(1000) null,
    requester_id int8 not null,
    constraint request_pk primary key(id),
    constraint request_user_fk foreign key(requester_id) references users(id)
);

CREATE TABLE IF NOT EXISTS items (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar(255) not NULL,
	description varchar(1000) not NULL,
	available bool NULL,
	owner_id int8 not NULL,
	request_id int8 null,
	CONSTRAINT item_pk PRIMARY KEY (id),
	CONSTRAINT item_user_fk FOREIGN KEY (owner_id) REFERENCES users(id),
	CONSTRAINT item_request_fk FOREIGN KEY (request_id) REFERENCES requests(id)
);

CREATE TABLE if not exists bookings (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	start_date timestamp without time zone NOT NULL,
	end_date timestamp without time zone NOT NULL,
	item_id int8 NOT NULL,
	booker_id int8 NOT NULL,
	status varchar NOT NULL,
	CONSTRAINT bookings_pk PRIMARY KEY (id),
	CONSTRAINT bookings_items_fk FOREIGN KEY (item_id) REFERENCES items(id),
	CONSTRAINT bookings_users_fk FOREIGN KEY (booker_id) REFERENCES users(id)
);

create table if not exists comments (
    id int8 generated BY DEFAULT AS IDENTITY NOT NULL,
    text varchar(1000) null,
    item_id int8 not null,
    author_id int8 not null,
    created timestamp without time zone not null,
    constraint comment_pk primary key(id),
    constraint comment_user_fk foreign key(author_id) references users(id),
    constraint comment_item_fk foreign key(item_id) references items(id)
);